services:
  aenyrathia-pgsql:
    image: "postgres:latest"
    ports:
      - 54322:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - aenyrathia-pgdata:/var/lib/postgresql/
volumes:
  aenyrathia-pgdata:
